CREATE TABLE gamelog (
	game_id VARCHAR(50) NOT NULL,
	game_date DATE NOT NULL,
	game_number CHAR(1) NOT NULL,
	day_of_week VARCHAR(10) NOT NULL,
	start_time INT(11) NOT NULL,
	dh_used_flag CHAR(1) NOT NULL,
	day_night_flag CHAR(1) NOT NULL,
	visiting_team CHAR(3) NOT NULL,
	home_team CHAR(3) NOT NULL,
	game_site VARCHAR(10) NOT NULL,
	vis_starting_pitcher VARCHAR(12) NOT NULL,
	home_starting_pitcher VARCHAR(12) NOT NULL,
	home_plate_umpire VARCHAR(12) NOT NULL,
	first_base_umpire VARCHAR(12) NOT NULL,
	second_base_umpire VARCHAR(12) NOT NULL,
	third_base_umpire VARCHAR(12) NOT NULL,
	left_field_umpire VARCHAR(12) NULL DEFAULT NULL,
	right_field_umpire VARCHAR(12) NULL DEFAULT NULL,
	attendance INT(11) NOT NULL,
	ps_scorer VARCHAR(100) NULL DEFAULT NULL,
	translator VARCHAR(50) NULL DEFAULT NULL,
	inputter VARCHAR(50) NULL DEFAULT NULL,
	input_time DATETIME NULL DEFAULT NULL,
	edit_time DATETIME NULL DEFAULT NULL,
	how_scored INT(11) NOT NULL,
	pitches_entered INT(11) NOT NULL,
	temperature INT(11) NOT NULL,
	wind_direction INT(11) NOT NULL,
	wind_speed INT(11) NOT NULL,
	field_condition INT(11) NOT NULL,
	precipitation INT(11) NOT NULL,
	sky INT(11) NOT NULL,
	time_of_game INT(11) NOT NULL,
	number_of_innings INT(11) NOT NULL,
	visitor_final_score INT(11) NOT NULL,
	home_final_score INT(11) NOT NULL,
	visitor_hits INT(11) NOT NULL,
	home_hits INT(11) NOT NULL,
	visitor_errors INT(11) NOT NULL,
	home_errors INT(11) NOT NULL,
	visitor_left_on_base INT(11) NOT NULL,
	home_left_on_base INT(11) NOT NULL,
	winning_pitcher CHAR(8) NOT NULL,
	losing_pitcher CHAR(8) NOT NULL,
	save_for CHAR(8) NOT NULL,
	gw_rbi CHAR(8) NOT NULL,
	visitor_batter_1 CHAR(8) NOT NULL,
	visitor_position_1 INT(11) NOT NULL,
	visitor_batter_2 CHAR(8) NOT NULL,
	visitor_position_2 INT(11) NOT NULL,
	visitor_batter_3 CHAR(8) NOT NULL,
	visitor_position_3 INT(11) NOT NULL,
	visitor_batter_4 CHAR(8) NOT NULL,
	visitor_position_4 INT(11) NOT NULL,
	visitor_batter_5 CHAR(8) NOT NULL,
	visitor_position_5 INT(11) NOT NULL,
	visitor_batter_6 CHAR(8) NOT NULL,
	visitor_position_6 INT(11) NOT NULL,
	visitor_batter_7 CHAR(8) NOT NULL,
	visitor_position_7 INT(11) NOT NULL,
	visitor_batter_8 CHAR(8) NOT NULL,
	visitor_position_8 INT(11) NOT NULL,
	visitor_batter_9 CHAR(8) NOT NULL,
	visitor_position_9 INT(11) NOT NULL,
	home_batter_1 CHAR(8) NOT NULL,
	home_position_1 INT(11) NOT NULL,
	home_batter_2 CHAR(8) NOT NULL,
	home_position_2 INT(11) NOT NULL,
	home_batter_3 CHAR(8) NOT NULL,
	home_position_3 INT(11) NOT NULL,
	home_batter_4 CHAR(8) NOT NULL,
	home_position_4 INT(11) NOT NULL,
	home_batter_5 CHAR(8) NOT NULL,
	home_position_5 INT(11) NOT NULL,
	home_batter_6 CHAR(8) NOT NULL,
	home_position_6 INT(11) NOT NULL,
	home_batter_7 CHAR(8) NOT NULL,
	home_position_7 INT(11) NOT NULL,
	home_batter_8 CHAR(8) NOT NULL,
	home_position_8 INT(11) NOT NULL,
	home_batter_9 CHAR(8) NOT NULL,
	home_position_9 INT(11) NOT NULL,
	extra_player_1 CHAR(8) NULL DEFAULT NULL,
	extra_player_2 CHAR(8) NULL DEFAULT NULL
);
